alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
features:
- buildpack-stack=ubuntu-22
ingress:
  rules:
  - component:
      name: umbilical
    match:
      path:
        prefix: /
  - component:
      name: grafana
    match:
      path:
        prefix: /grafana
name: umbilical
region: nyc
services:
- dockerfile_path: Dockerfile
  envs:
  - key: WEBPUSH_JWK_BASE64
    scope: RUN_AND_BUILD_TIME
    value: 
  - key: WEBPUSH_SUB
    scope: RUN_AND_BUILD_TIME
    value: 
  - key: PI_API_KEY
    scope: RUN_AND_BUILD_TIME
    value: 
  - key: PI_API_SECRET
    scope: RUN_AND_BUILD_TIME
    value: 
  - key: UMBILICAL_KEYS
    scope: RUN_AND_BUILD_TIME
    value: 
  - key: ENABLED_FEATURES
    scope: RUN_AND_BUILD_TIME
    value: proxy,search,podping_websocket,podping_webpush,podroll,oauth2
  - key: DEBUG
    scope: RUN_AND_BUILD_TIME
    value: "false"
  - key: WEBPUSH_TEMPLATE
    scope: RUN_AND_BUILD_TIME
    value: angular
  - key: OAUTH2_CONFIG
    scope: RUN_AND_BUILD_TIME
    value: 
  - key: OTEL_EXPORTER_OTLP_ENDPOINT
    scope: RUN_AND_BUILD_TIME
    value: http://otel-collector:4318
  github:
    branch: main
    deploy_on_push: true
    repo: aegrumet/umbilical
  http_port: 8000
  instance_count: 1
  instance_size_slug: basic-xxs
  name: umbilical
  source_dir: /
- dockerfile_path: docker/Docker.collector
  github:
    branch: main
    repo: aegrumet/umbilical
    deploy_on_push: false
  instance_count: 1
  instance_size_slug: basic-xxs
  internal_ports:
  - 4318
  - 8889
  name: otel-collector
  source_dir: /
- dockerfile_path: docker/Docker.prometheus
  github:
    branch: main
    repo: aegrumet/umbilical
    deploy_on_push: false
  instance_count: 1
  instance_size_slug: basic-xxs
  internal_ports:
  - 9090
  name: prometheus
  source_dir: /
- dockerfile_path: docker/Docker.grafana
  envs:
  - key: GF_SERVER_ROOT_URL
    scope: RUN_AND_BUILD_TIME
    value: ${APP_URL}/grafana/
  - key: GF_SECURITY_ADMIN_USER
    scope: RUN_AND_BUILD_TIME
    value: 
  - key: GF_SECURITY_ADMIN_PASSWORD
    scope: RUN_AND_BUILD_TIME
    value: 
  github:
    branch: main
    repo: aegrumet/umbilical
    deploy_on_push: false
  http_port: 3000
  instance_count: 1
  instance_size_slug: basic-xxs
  name: grafana
  source_dir: /
